"""add the answer column

Revision ID: 21722cbb674e
Revises: 8b398c96a16f
Create Date: 2019-12-15 14:51:54.193029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21722cbb674e'
down_revision = '8b398c96a16f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sick_request', sa.Column('answer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sick_request', 'answer')
    # ### end Alembic commands ###
