"""empty message

Revision ID: 38cdc94e3672
Revises: 841799a1a7a2
Create Date: 2019-12-17 05:38:55.110998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38cdc94e3672'
down_revision = '841799a1a7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('authenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor', 'authenticated')
    # ### end Alembic commands ###
