"""add the medicine column

Revision ID: 474eb1ade622
Revises: 21722cbb674e
Create Date: 2019-12-16 10:27:10.289762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474eb1ade622'
down_revision = '21722cbb674e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('medicines', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'medicines')
    # ### end Alembic commands ###
