"""empty message

Revision ID: 841799a1a7a2
Revises: c959bf38cbdc
Create Date: 2019-12-16 15:42:59.429211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841799a1a7a2'
down_revision = 'c959bf38cbdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('doc_mail', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor', 'doc_mail')
    # ### end Alembic commands ###
