"""empty message

Revision ID: c959bf38cbdc
Revises: e0afce1b91ad
Create Date: 2019-12-16 15:37:28.499526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c959bf38cbdc'
down_revision = 'e0afce1b91ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('doc_pass', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor', 'doc_pass')
    # ### end Alembic commands ###
