"""empty message

Revision ID: dbea4370423f
Revises: 38cdc94e3672
Create Date: 2019-12-17 15:07:00.823801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbea4370423f'
down_revision = '38cdc94e3672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('image_profile', sa.String(length=50), nullable=True))
    op.add_column('sick_request', sa.Column('image_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sick_request', 'image_file')
    op.drop_column('doctor', 'image_profile')
    # ### end Alembic commands ###
