"""empty message

Revision ID: e7c3b2f4752a
Revises: dbea4370423f
Create Date: 2019-12-18 14:56:01.572867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c3b2f4752a'
down_revision = 'dbea4370423f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('birth_place', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'birth_place')
    # ### end Alembic commands ###
